name: Netlify Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.4.4

    - name: Deploy to Netlify
      run: |
        curl -X POST -d '{}' -H 'Content-Type: application/json' -u ${{ secrets.NETLIFY_BASIC_AUTH_USER }}:${{ secrets.NETLIFY_BASIC_AUTH_PASSWORD }} https://api.netlify.com/api/v1/sites/bed74570-5637-4a88-9daf-4eda431e0ae9/build
